"""Deterministic provider used for local development and tests."""

from __future__ import annotations

import json
import time
from typing import Any

from app.cost import calculate_cost
from app.features import approximate_token_count, get_prompt_text
from app.providers.base import BaseLLMProvider, ProviderResponse


class MockProvider(BaseLLMProvider):
    provider_name = "mock"

    def chat_completion(
        self,
        messages: list[dict[str, str]],
        model_config: dict,
        temperature: float,
        max_tokens: int,
    ) -> ProviderResponse:
        start_time = time.perf_counter()
        prompt = get_prompt_text(messages)
        text = _build_mock_response(prompt, model_config)

        input_tokens = approximate_token_count(prompt)
        output_tokens = min(max_tokens, max(8, approximate_token_count(text)))
        total_cost = calculate_cost(input_tokens, output_tokens, model_config)
        latency_ms = round((time.perf_counter() - start_time) * 1000, 2)

        return ProviderResponse(
            text=text,
            provider=str(model_config.get("provider", "mock")),
            model_id=str(model_config.get("model_id", "mock-model")),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_cost=total_cost,
            latency_ms=latency_ms,
            raw_response={
                "mock": True,
                "temperature": temperature,
                "max_tokens": max_tokens,
            },
        )


def _build_mock_response(prompt: str, model_config: dict[str, Any]) -> str:
    display_name = model_config.get("display_name", model_config.get("model_id", "mock model"))
    lowered = prompt.lower()
    prompt_preview = " ".join(prompt.strip().split())[:160]

    if "json" in lowered:
        return json.dumps(
            {
                "status": "mock",
                "summary": "Deterministic JSON response",
                "model": display_name,
            }
        )

    if "bullet" in lowered or "bullets" in lowered:
        return (
            f"- Mock response generated by {display_name}\n"
            "- The router selected this model from configuration\n"
            "- No paid API call was made"
        )

    return (
        f"Mock response from {display_name}: {prompt_preview}"
        if prompt_preview
        else f"Mock response from {display_name}."
    )
